version: '3'
services:
  cheese-graphql-api:
    container_name: ${CONTAINER_NAME}
    build: .
    depends_on:
      - postgres
    expose:
      - '8000'
    ports:
      - 8000:${GRAPHQL_APP_PORT}
    user: node
    volumes:
      - ./:/app
    working_dir: '/app'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${GRAPHQL_APP_PORT}
    tty: true
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5000:${DB_PORT}'