type Post {
  id: String!
  title: String!
  text: String!
  url: String!
  created_at: String!
  thumbnail: String
  description: String
  user: User!
}

extend type Query {
  posts: [Post]
  post(id: String!): Post
}
