input UserData {
  email: String
  username: String!
  password: String!
  role: String
  avatar: String
}

type User {
  email: String!
  username: String!
  role: String
  id: ID!
  avatar: String
}

type AuthResponse {
  token: String
}

extend type Query {
  me: User
  users: [User]
  user(id: ID!): User
}

extend type Mutation {
  signup(input: UserData!): AuthResponse
  login(input: UserData!): AuthResponse
}
