input userData {
  email: String!
  username: String!
  password: String!
  role: String
}

type authResponse {
  token: String
}

extend type Mutation {
  signup(input: userData!): authResponse!
  login(input: userData!): authResponse!
}