input UserData {
  email: String!
  username: String!
  password: String!
  role: String
}

type User {
  email: String!
  username: String!
  password: String
  role: String
}

type AuthResponse {
  token: String
}

extend type Query {
  me: User
}

extend type Mutation {
  signup(input: UserData!): AuthResponse
  login(input: UserData!): AuthResponse
}
